# Generated by Django 4.1.3 on 2022-12-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('done', models.CharField(choices=[(1, 'Open'), (2, 'Closed')], max_length=1)),
                ('initial_date', models.DateTimeField(auto_now_add=True)),
                ('final_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
