# Generated by Django 4.1.3 on 2022-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], max_length=6),
        ),
    ]
